## 課題2.1(必須)



### 2.1.1


In [1]:
# LU decomposition
function ludecomp!(A)
    n = size(A)[1]
    for j = 1:n
        # u_{ij} (i <= j)
        for i = 1:j
            u = A[i,j]
            for k = 1:(i-1)
                u -= A[i,k]*A[k,j]
            end
            A[i,j] = u
        end
        # l_{ij} (i > j)
        for i = (j+1):n
            l = A[i,j]
            for k = 1:(j-1)
                l -= A[i,k]*A[k,j]
            end
            A[i,j] = l/A[j,j]
        end
    end
    return A
end


# main
function main()
    A = [3. 1. 1.
         1. 3. 1.
         1. 1. 3.]
    println("LU=")
    Base.print_array(IOContext(stdout, :compact => true), ludecomp!(A))
end


main()

LU=
 3.0       1.0      1.0     
 0.333333  2.66667  0.666667
 0.333333  0.25     2.5     

### ライブラリを用いる
```julia
using LinearAlgebra
lu(A)
```

In [11]:
using LinearAlgebra
A = [3. 1. 1.
     1. 3. 1.
     1. 1. 3.]

println("L=")
Base.print_array(IOContext(stdout, :compact => true), lu(A).L)
println("\nU=")
Base.print_array(IOContext(stdout, :compact => true), lu(A).U)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0   0.0
 0.333333  1.0   0.0
 0.333333  0.25  1.0
U factor:
3×3 Array{Float64,2}:
 3.0  1.0      1.0     
 0.0  2.66667  0.666667
 0.0  0.0      2.5     

L=
 1.0       0.0   0.0
 0.333333  1.0   0.0
 0.333333  0.25  1.0
U=
 3.0  1.0      1.0     
 0.0  2.66667  0.666667
 0.0  0.0      2.5     

### 2.1.2

In [2]:
# Forward Substitution
function fwdsub!(L, b)
    for i = 1:size(b)[1]
        y = b[i]
        for k = 1:i-1
            y -= b[k]*L[i,k]
        end
        b[i] = y
    end
    return b
end


# main
function main()
    L = [1.0      0.0  0.0     
         0.333333 1.0  0.0
         0.333333 0.25 1.0]
    b=[0.; 4.; 6.]
    fwdsub!(L, b)
end


main()

3-element Array{Float64,1}:
 0.0
 4.0
 5.0

### 2.1.3

In [3]:
# Backward Substitution
function bwdsub!(U, y)
    n = size(y)[1]
    for i = n:-1:1
        x = y[i]
        for k = (i+1):n
            x -= y[k]*U[i,k]
        end
        y[i] = x/U[i,i]
    end
    return y
end


# main
function main()
    U = [3.0 1.0     1.0     
         0.0 2.66667 0.666667
         0.0 0.0     2.5]
    y=[0.; 4.; 5.]
    bwdsub!(U, y)
end


main()

3-element Array{Float64,1}:
 -0.9999995000006251
  0.9999985000018751
  2.0               

### 2.1.4

In [5]:
# simultaneous linear equations solution
function lusolve!(A, b)
    ludecomp!(A)
    fwdsub!(A, b)
    bwdsub!(A, b)
end


# main
function main()
    A = [3. 1. 1.
         1. 3. 1. 
         1. 1. 3.]
    b=[0.; 4.; 6.]

    println("A=", A)
    println("b=", b)
    println("x=", lusolve!(A,b))
end


main()

A=[3.0 1.0 1.0; 1.0 3.0 1.0; 1.0 1.0 3.0]
b=[0.0, 4.0, 6.0]
x=[-1.0, 1.0, 2.0]


### 2.1.5


In [6]:
using LinearAlgebra


# A matrix
function amtx(n, a)
    mtx = Array(SymTridiagonal(fill(1., n), fill(a, n-1)))
    mtx[1,n] = mtx[n,1] = a
    return mtx
end


# b vector
function bvec(n)
    vec = zeros(n,1)
    vec[1] = 1
    vec[n] = -1
    return vec
end


# main
function main()
    n = 50
    println(lusolve!(amtx(n, -1/4), bvec(n)))
    println(lusolve!(amtx(n, -3/4), bvec(n)))
end


main()

[0.845299; 0.226497; 0.0606898; 0.0162618; 0.00435733; 0.00116754; 0.000312842; 8.38258e-5; 2.24611e-5; 6.01842e-6; 1.61263e-6; 4.32103e-7; 1.15782e-7; 3.10236e-8; 8.31275e-9; 2.2274e-9; 5.96829e-10; 1.5992e-10; 4.28504e-11; 1.14817e-11; 3.0765e-12; 8.24269e-13; 2.20579e-13; 5.80471e-14; 1.16094e-14; -1.16094e-14; -5.80471e-14; -2.20579e-13; -8.24269e-13; -3.0765e-12; -1.14817e-11; -4.28504e-11; -1.5992e-10; -5.96829e-10; -2.2274e-9; -8.31275e-9; -3.10236e-8; -1.15782e-7; -4.32103e-7; -1.61263e-6; -6.01842e-6; -2.24611e-5; -8.38258e-5; -0.000312842; -0.00116754; -0.00435733; -0.0162618; -0.0606898; -0.226497; -0.845299]
[0.873435; 0.704681; 0.06614; -0.616494; -0.888133; -0.567682; 0.131223; 0.742646; 0.858972; 0.40265; -0.322105; -0.832124; -0.787393; -0.217733; 0.497082; 0.880509; 0.67693; 0.0220648; -0.647511; -0.885412; -0.533039; 0.174693; 0.765964; 0.846591; 0.362825; -0.362825; -0.846591; -0.765964; -0.174693; 0.533039; 0.885412; 0.647511; -0.0220648; -0.67693; -0.880509; -0.497